kinda finalize workflow

diff --git a/bin/batch_l1_status_checker b/bin/batch_l1_status_checker
--- a/bin/batch_l1_status_checker
+++ b/bin/batch_l1_status_checker
@@ -1,11 +1,25 @@
 #!/bin/bash
 
-# Configuration
-URL="http://127.0.0.1:3052/"
-INTERVAL=10 # Time interval in seconds
+# Needs following configuration
+# URL - URL of the API endpoint
+# INTERVAL - Time interval for polling in seconds
+# TIMEOUT - Timeout of script in seconds
+
+# Start timer
+START_TIME=$(date +%s)
 
 # Loop to query periodically
 while true; do
+    # Calculate the elapsed time
+    CURRENT_TIME=$(date +%s)
+    ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
+
+    # Check if the timeout has been reached
+    if [ $ELAPSED_TIME -ge $TIMEOUT ]; then
+        echo "Timeout reached. Failing CI..."
+        exit 1  # Exit with non-zero status to fail CI
+    fi
+
     # Run the curl request and capture the response
     RESPONSE=$(curl --silent --request POST \
         --url $URL \
@@ -24,7 +38,7 @@ while true; do
     if [ "$EXECUTED_AT" != "null" ] && [ -n "$EXECUTED_AT" ]; then
         echo "executedAt is not null: $EXECUTED_AT"
         echo "true"
-        break
+        exit 0  # Exit with zero status to succeed CI
     else
         echo "executedAt is null, retrying in $INTERVAL seconds..."
     fi
