Update zk
-Added some comments for a cleaner understanding of how the script works
-Added an error handler and implemented it on some potentially risky places

diff --git a/bin/zk b/bin/zk
--- a/bin/zk
+++ b/bin/zk
@@ -1,23 +1,31 @@
 #!/usr/bin/env bash
 
+# Define color codes for formatting output
 RED='\033[0;31m'
 WHITE_BOLD='\033[1;37m'
 NC='\033[0m' # No Color
 
-# checks that the current directory that user is in, is inside the $ZKSYNC_HOME.
+# Error handling function
+handle_error() {
+    echo "Error: $1" >&2
+    exit 1
+}
+
+# Checks that the current directory that user is in, is inside the $ZKSYNC_HOME.
 # We depend on this variable in multiple places - so running from a different directory might have
 # some surprising side effects (like loading wrong binaries etc).
 check_subdirectory() {
     if [[ -z "$ZKSYNC_HOME" ]]; then
-        echo -e "${RED}Error: ZKSYNC_HOME is not set.${NC}"
+        echo -e "${RED}Error: ZKSYNC_HOME is not set.${NC}" >&2
         return 1
     fi
 
+    # Resolve absolute paths
     ZKSYNC_HOME_ABS=$(realpath "$ZKSYNC_HOME")
     CURRENT_DIR_ABS=$(realpath .)
 
     if [[ "$CURRENT_DIR_ABS" != "$ZKSYNC_HOME_ABS"* ]]; then
-        echo -e "${RED}Warning: You are not in a subdirectory of ZKSYNC_HOME ($ZKSYNC_HOME_ABS).${NC}"
+        echo -e "${RED}Warning: You are not in a subdirectory of ZKSYNC_HOME ($ZKSYNC_HOME_ABS).${NC}" >&2
         return 1
     fi
     return 0
@@ -30,8 +38,8 @@ check_yarn_version() {
     installed_version=$(yarn --version | cut -d'.' -f1,2)
 
     if [ "$installed_version" != "$desired_version" ]; then
-        echo -e "${RED}Warning: Yarn is not at the desired version ($desired_version). Installed version is ($installed_version).${NC}"
-        echo -e "This might cause errors - we recommend to run: ${WHITE_BOLD} yarn set version $desired_version.${NC}"
+        echo -e "${RED}Warning: Yarn is not at the desired version ($desired_version). Installed version is ($installed_version).${NC}" >&2
+        echo -e "This might cause errors - we recommend to run: ${WHITE_BOLD} yarn set version $desired_version.${NC}" >&2
     fi
 }
 
@@ -40,9 +48,9 @@ check_yarn_version() {
 check_subdirectory
 check_yarn_version
 if [ -z "$1" ]; then
-    cd $ZKSYNC_HOME
-    yarn install --frozen-lockfile && yarn zk build
+    cd $ZKSYNC_HOME || handle_error "Failed to change directory to '$ZKSYNC_HOME'."
+    yarn install --frozen-lockfile && yarn zk build || handle_error "Failed to execute Yarn commands."
 else
-    # can't start this with yarn since it has quirks with `--` as an argument
-    node -- $ZKSYNC_HOME/infrastructure/zk/build/index.js "$@"
+    # Сan't start this with yarn since it has quirks with `--` as an argument
+    node -- $ZKSYNC_HOME/infrastructure/zk/build/index.js "$@" || handle_error "Failed to execute Node command."
 fi
