feat: add bin folder to path in zkstackup

diff --git a/zkstack_cli/zkstackup/zkstackup b/zkstack_cli/zkstackup/zkstackup
--- a/zkstack_cli/zkstackup/zkstackup
+++ b/zkstack_cli/zkstackup/zkstackup
@@ -30,6 +30,8 @@ main() {
 
   zkstack_banner
 
+  add_bin_folder_to_path
+
   for bin in "${BINS[@]}"; do
     success "Installed $bin to $BIN_DIR/$bin"
   done
@@ -168,6 +170,50 @@ install_from_repo() {
   else
     ensure cargo install --root $LOCAL_DIR --git "https://github.com/$ZKSTACKUP_REPO" --locked "${BINS[@]}" --force
   fi
+}
+
+add_bin_folder_to_path() {
+  if [[ ":$PATH:" == *":${BIN_DIR}:"* ]]; then
+    echo "zkstackup: found ${BIN_DIR} in PATH"
+    exit 0
+  fi
+
+  case $SHELL in
+  */zsh)
+    PROFILE="${ZDOTDIR-"$HOME"}/.zshenv"
+    ;;
+  */bash)
+    PROFILE="$HOME/.bashrc"
+    ;;
+  */fish)
+    PROFILE="$HOME/.config/fish/config.fish"
+    ;;
+  */ash)
+    PROFILE="$HOME/.profile"
+    ;;
+  *)
+    echo "zkstackup: could not detect shell, manually add ${BIN_DIR} to your PATH."
+    exit 1
+    ;;
+  esac
+
+  if [[ ! -f "$PROFILE" ]]; then
+    echo "zkstackup: Profile file $PROFILE does not exist, creating it."
+    touch "$PROFILE"
+  fi
+
+  if [[ "$SHELL" == *"/fish"* ]]; then
+    echo -e "\n# Added by zkstackup\nfish_add_path -a $BIN_DIR" >>"$PROFILE"
+    echo "zkstackup: Added $BIN_DIR to PATH in $PROFILE using fish_add_path."
+  else
+    echo -e "\n# Added by zkstackup\nexport PATH=\"\$PATH:$BIN_DIR\"" >>"$PROFILE"
+    echo "zkstackup: Added $BIN_DIR to PATH in $PROFILE."
+  fi
+
+  echo
+  echo "Added zkstackup to PATH."
+  echo "Run 'source $PROFILE' or start a new terminal session to use zkstackup."
+  echo "Then run 'zkstackup' to install ZK Stack CLI."
 }
 
 ensure() {
