Add install_local

diff --git a/zk_toolbox/zkup/zkup b/zk_toolbox/zkup/zkup
--- a/zk_toolbox/zkup/zkup
+++ b/zk_toolbox/zkup/zkup
@@ -5,13 +5,17 @@ BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
 ZKT_DIR=${ZKT_DIR:-"$BASE_DIR/.zkt"}
 ZKT_BIN_DIR="$ZKT_DIR/bin"
 
-BINS=(zk_inception zk_supervisor)
-
-export RUSTFLAGS="${RUSTFLAGS:--C target-cpu=native}"
+ZKUP_SKIP_ZK_SUPERVISOR=0
 
 main() {
   check_prerequisites
   parse_args "$@"
+
+  if [ -n "$ZKUP_PATH" ]; then
+    install_local
+  fi
+
+  echo "zk_toolbox installed successfully"
 }
 
 PREREQUISITES=(cargo git curl)
@@ -41,10 +45,11 @@ parse_args() {
     -r | --repo)      shift; ZKUP_REPO=$1;;
     -b | --branch)    shift; ZKUP_BRANCH=$1;;
     -c | --commit)    shift; ZKUP_COMMIT=$1;;
-    -p | --path)      shift; ZKUP_LOCAL_REPO=$1;;
+    -p | --path)      shift; ZKUP_PATH=$1;;
     -v | --version)   shift; ZKUP_VERSION=$1;;
     -a | --arch)      shift; ZKUP_ARCH=$1;;
     -P | --platform)  shift; ZKUP_PLATFORM=$1;;
+    --skip-zk-supervisor) ZKUP_SKIP_ZK_SUPERVISOR=1;;
     -h | --help)
       usage
       exit 0
@@ -64,6 +69,29 @@ usage() {
 zkup - zkup installer
 Usage placeholder
 EOF
+}
+
+install_local() {
+  if [ ! -d "$ZKUP_PATH" ]; then
+    echo "Path $ZKUP_PATH does not exist"
+    exit 1
+  fi
+
+  if [ -n "$ZKUP_BRANCH" ] || [ -n "$ZKUP_COMMIT" ] || [ -n "$ZKUP_VERSION" ]; then
+    echo "Ignoring --branch, --commit and --version arguments when installing from local path"
+  fi
+
+  echo "Installing zkup from $ZKUP_PATH"
+  cd "$ZKUP_PATH"/zk_toolbox
+
+  ensure cargo install --path ./crates/zk_inception --force
+  if [ $ZKUP_SKIP_ZK_SUPERVISOR -eq 0 ]; then
+    ensure cargo install --path ./crates/zk_supervisor --force
+  fi
+}
+
+ensure() {
+  if ! "$@"; then err "command failed: $*"; fi
 }
 
 main "$@"
