test multiarch

diff --git a/.github/workflows/build-prover-template.yml b/.github/workflows/build-prover-template.yml
--- a/.github/workflows/build-prover-template.yml
+++ b/.github/workflows/build-prover-template.yml
@@ -65,115 +65,115 @@ jobs:
           echo CI=1 >> .env
           echo IN_DOCKER=1 >> .env
 
-      - name: start-services
-        run: |
-          echo "IMAGE_TAG_SUFFIX=${{ env.IMAGE_TAG_SUFFIX }}" >> .env
-          docker-compose -f docker-compose-runner.yml up -d zk geth postgres
-          ci_run sccache --start-server
+      # - name: start-services
+      #   run: |
+      #     echo "IMAGE_TAG_SUFFIX=${{ env.IMAGE_TAG_SUFFIX }}" >> .env
+      #     docker-compose -f docker-compose-runner.yml up -d zk geth postgres
+      #     ci_run sccache --start-server
 
-      - name: init
-        run: |
-          ci_run git config --global --add safe.directory /usr/src/zksync
-          ci_run git config --global --add safe.directory /usr/src/zksync/sdk/binaryen
-          ci_run git config --global --add safe.directory /usr/src/zksync/etc/system-contracts
-          ci_run git config --global --add safe.directory /usr/src/zksync/contracts
-          ci_run zk
-          ci_run zk clean --all
-          ci_run zk run yarn
-          ci_run cp etc/tokens/{test,localhost}.json
-          ci_run zk compiler all
-          ci_run zk contract build
-          ci_run zk f yarn run l2-contracts build
-          ci_run curl -LO https://storage.googleapis.com/matterlabs-setup-keys-us/setup-keys/setup_2\^26.key
+      # - name: init
+      #   run: |
+      #     ci_run git config --global --add safe.directory /usr/src/zksync
+      #     ci_run git config --global --add safe.directory /usr/src/zksync/sdk/binaryen
+      #     ci_run git config --global --add safe.directory /usr/src/zksync/etc/system-contracts
+      #     ci_run git config --global --add safe.directory /usr/src/zksync/contracts
+      #     ci_run zk
+      #     ci_run zk clean --all
+      #     ci_run zk run yarn
+      #     ci_run cp etc/tokens/{test,localhost}.json
+      #     ci_run zk compiler all
+      #     ci_run zk contract build
+      #     ci_run zk f yarn run l2-contracts build
+      #     ci_run curl -LO https://storage.googleapis.com/matterlabs-setup-keys-us/setup-keys/setup_2\^26.key
 
-      - name: login to Docker registries
-        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
-        run: |
-          ci_run docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
-          ci_run gcloud auth configure-docker us-docker.pkg.dev,asia-docker.pkg.dev,europe-docker.pkg.dev -q
+      # - name: login to Docker registries
+      #   if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
+      #   run: |
+      #     ci_run docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
+      #     ci_run gcloud auth configure-docker us-docker.pkg.dev,asia-docker.pkg.dev,europe-docker.pkg.dev -q
 
-      # We need to run this only when ERA_BELLMAN_CUDA_RELEASE is not available
-      # In our case it happens only when PR is created from fork
-      - name: Wait for runner IP to be not rate-limited against GH API
-        if: inputs.is_pr_from_fork == true
-        run: |
-          api_endpoint="https://api.github.com/users/zksync-era-bot"
-          wait_time=60
-          max_retries=60
-          retry_count=0
+      # # We need to run this only when ERA_BELLMAN_CUDA_RELEASE is not available
+      # # In our case it happens only when PR is created from fork
+      # - name: Wait for runner IP to be not rate-limited against GH API
+      #   if: inputs.is_pr_from_fork == true
+      #   run: |
+      #     api_endpoint="https://api.github.com/users/zksync-era-bot"
+      #     wait_time=60
+      #     max_retries=60
+      #     retry_count=0
 
-          while [[ $retry_count -lt $max_retries ]]; do
-            response=$(curl -s -w "%{http_code}" -o temp.json "$api_endpoint")
-            http_code=$(echo "$response" | tail -n1)
+      #     while [[ $retry_count -lt $max_retries ]]; do
+      #       response=$(curl -s -w "%{http_code}" -o temp.json "$api_endpoint")
+      #       http_code=$(echo "$response" | tail -n1)
 
-            if [[ "$http_code" == "200" ]]; then
-              echo "Request successful. Not rate-limited."
-              cat temp.json
-              rm temp.json
-              exit 0
-            elif [[ "$http_code" == "403" ]]; then
-              rate_limit_exceeded=$(jq -r '.message' temp.json | grep -i "API rate limit exceeded")
-              if [[ -n "$rate_limit_exceeded" ]]; then
-                retry_count=$((retry_count+1))
-                echo "API rate limit exceeded. Retry $retry_count of $max_retries. Retrying in $wait_time seconds..."
-                sleep $wait_time
-              else
-                echo "Request failed with HTTP status $http_code."
-                cat temp.json
-                rm temp.json
-                exit 1
-              fi
-            else
-              echo "Request failed with HTTP status $http_code."
-              cat temp.json
-              rm temp.json
-              exit 1
-            fi
-          done
+      #       if [[ "$http_code" == "200" ]]; then
+      #         echo "Request successful. Not rate-limited."
+      #         cat temp.json
+      #         rm temp.json
+      #         exit 0
+      #       elif [[ "$http_code" == "403" ]]; then
+      #         rate_limit_exceeded=$(jq -r '.message' temp.json | grep -i "API rate limit exceeded")
+      #         if [[ -n "$rate_limit_exceeded" ]]; then
+      #           retry_count=$((retry_count+1))
+      #           echo "API rate limit exceeded. Retry $retry_count of $max_retries. Retrying in $wait_time seconds..."
+      #           sleep $wait_time
+      #         else
+      #           echo "Request failed with HTTP status $http_code."
+      #           cat temp.json
+      #           rm temp.json
+      #           exit 1
+      #         fi
+      #       else
+      #         echo "Request failed with HTTP status $http_code."
+      #         cat temp.json
+      #         rm temp.json
+      #         exit 1
+      #       fi
+      #     done
 
-          echo "Reached the maximum number of retries ($max_retries). Exiting."
-          rm temp.json
-          exit 1
+      #     echo "Reached the maximum number of retries ($max_retries). Exiting."
+      #     rm temp.json
+      #     exit 1
 
-      - name: update-images
-        env:
-          DOCKER_ACTION: ${{ inputs.action }}
-          COMPONENT: ${{ matrix.component }}
-          RUST_NIGHTLY_COMPONENTS: |
-            (
-              "witness-generator"
-              "prover-v2"
-              "circuit-synthesizer"
-              "prover-fri"
-              "prover-gpu-fri"
-              "witness-vector-generator"
-              "prover-fri-gateway"
-              "proof-fri-compressor"
-            )
-        run: |
-          nightly_components=${{ env.RUST_NIGHTLY_COMPONENTS }}
+      # - name: update-images
+      #   env:
+      #     DOCKER_ACTION: ${{ inputs.action }}
+      #     COMPONENT: ${{ matrix.component }}
+      #     RUST_NIGHTLY_COMPONENTS: |
+      #       (
+      #         "witness-generator"
+      #         "prover-v2"
+      #         "circuit-synthesizer"
+      #         "prover-fri"
+      #         "prover-gpu-fri"
+      #         "witness-vector-generator"
+      #         "prover-fri-gateway"
+      #         "proof-fri-compressor"
+      #       )
+      #   run: |
+      #     nightly_components=${{ env.RUST_NIGHTLY_COMPONENTS }}
 
-          if [[ " ${nightly_components[*]} " =~ " ${COMPONENT} " ]]; then
-            underscored_name=$(echo "$COMPONENT" | tr '-' '_')
-            # Hack: prover-v2 codebase located in prover directory instead of prover_v2
-            if [ "$underscored_name" == "prover_v2" ]; then
-              underscored_name="prover"
-            fi
-            # prover-gpu-fri codebase located in prover_fri directory instead of prover_gpu_fri
-            if [ "$underscored_name" == "prover_gpu_fri" ]; then
-              underscored_name="prover_fri"
-            fi
-            ci_run echo [workspace] > Cargo.toml
-            ci_run echo members = [\"prover/${underscored_name}\"] >> Cargo.toml
-            ci_run cp prover/Cargo.lock Cargo.lock
-            PASSED_ENV_VARS="ERA_BELLMAN_CUDA_RELEASE"  \
-            ci_run zk docker $DOCKER_ACTION $COMPONENT
-          else
-            ci_run zk docker $DOCKER_ACTION $COMPONENT
-          fi
+      #     if [[ " ${nightly_components[*]} " =~ " ${COMPONENT} " ]]; then
+      #       underscored_name=$(echo "$COMPONENT" | tr '-' '_')
+      #       # Hack: prover-v2 codebase located in prover directory instead of prover_v2
+      #       if [ "$underscored_name" == "prover_v2" ]; then
+      #         underscored_name="prover"
+      #       fi
+      #       # prover-gpu-fri codebase located in prover_fri directory instead of prover_gpu_fri
+      #       if [ "$underscored_name" == "prover_gpu_fri" ]; then
+      #         underscored_name="prover_fri"
+      #       fi
+      #       ci_run echo [workspace] > Cargo.toml
+      #       ci_run echo members = [\"prover/${underscored_name}\"] >> Cargo.toml
+      #       ci_run cp prover/Cargo.lock Cargo.lock
+      #       PASSED_ENV_VARS="ERA_BELLMAN_CUDA_RELEASE"  \
+      #       ci_run zk docker $DOCKER_ACTION $COMPONENT
+      #     else
+      #       ci_run zk docker $DOCKER_ACTION $COMPONENT
+      #     fi
 
-      - name: Show sccache stats
-        if: always()
-        run: |
-          ci_run sccache --show-stats
-          ci_run cat /tmp/sccache_log.txt
+      # - name: Show sccache stats
+      #   if: always()
+      #   run: |
+      #     ci_run sccache --show-stats
+      #     ci_run cat /tmp/sccache_log.txt
