turn off loadtest

diff --git a/.github/workflows/ci-core-reusable.yml b/.github/workflows/ci-core-reusable.yml
--- a/.github/workflows/ci-core-reusable.yml
+++ b/.github/workflows/ci-core-reusable.yml
@@ -68,85 +68,85 @@ jobs:
           ci_run cargo test --release -p vm-benchmark --bench oneshot --bench batch
 
   # FIXME: support loadtest together with sync layer.
-  loadtest:
-    runs-on: [ matterlabs-ci-runner-high-performance ]
-    strategy:
-      fail-fast: false
-      matrix:
-      # FIXME: support new VM mode
-        vm_mode: ["OLD"]
+  # loadtest:
+  #   runs-on: [ matterlabs-ci-runner-high-performance ]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #     # FIXME: support new VM mode
+  #       vm_mode: ["OLD"]
 
-    steps:
-      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
-        with:
-          submodules: "recursive"
-          fetch-depth: 0
+  #   steps:
+  #     - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
+  #       with:
+  #         submodules: "recursive"
+  #         fetch-depth: 0
 
-      - name: Setup environment
-        run: |
-          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
-          echo $(pwd)/bin >> $GITHUB_PATH
-          echo IN_DOCKER=1 >> .env
+  #     - name: Setup environment
+  #       run: |
+  #         echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
+  #         echo $(pwd)/bin >> $GITHUB_PATH
+  #         echo IN_DOCKER=1 >> .env
 
-      - name: Loadtest configuration
-        run: |
-          echo EXPECTED_TX_COUNT=${{ matrix.vm_mode == 'NEW' && 21000 || 16000 }} >> .env
-          echo ACCOUNTS_AMOUNT="100" >> .env
-          echo MAX_INFLIGHT_TXS="10" >> .env
-          echo SYNC_API_REQUESTS_LIMIT="15" >> .env
-          echo FAIL_FAST=true >> .env
-          echo IN_DOCKER=1 >> .env
+  #     - name: Loadtest configuration
+  #       run: |
+  #         echo EXPECTED_TX_COUNT=${{ matrix.vm_mode == 'NEW' && 21000 || 16000 }} >> .env
+  #         echo ACCOUNTS_AMOUNT="100" >> .env
+  #         echo MAX_INFLIGHT_TXS="10" >> .env
+  #         echo SYNC_API_REQUESTS_LIMIT="15" >> .env
+  #         echo FAIL_FAST=true >> .env
+  #         echo IN_DOCKER=1 >> .env
 
-      - name: Start services
-        run: |
-          ci_localnet_up
-          ci_run sccache --start-server
+  #     - name: Start services
+  #       run: |
+  #         ci_localnet_up
+  #         ci_run sccache --start-server
 
-      - name: Init
-        run: |
-          ci_run git config --global --add safe.directory /usr/src/zksync
-          ci_run git config --global --add safe.directory /usr/src/zksync/sdk/binaryen
-          ci_run git config --global --add safe.directory /usr/src/zksync/contracts/system-contracts
-          ci_run git config --global --add safe.directory /usr/src/zksync/contracts
+  #     - name: Init
+  #       run: |
+  #         ci_run git config --global --add safe.directory /usr/src/zksync
+  #         ci_run git config --global --add safe.directory /usr/src/zksync/sdk/binaryen
+  #         ci_run git config --global --add safe.directory /usr/src/zksync/contracts/system-contracts
+  #         ci_run git config --global --add safe.directory /usr/src/zksync/contracts
 
-          ci_run ./bin/zkt
-          ci_run zk_inception chain create \
-            --chain-name legacy \
-            --chain-id sequential \
-            --prover-mode no-proofs \
-            --wallet-creation localhost \
-            --l1-batch-commit-data-generator-mode rollup \
-            --base-token-address 0x0000000000000000000000000000000000000001 \
-            --base-token-price-nominator 1 \
-            --base-token-price-denominator 1 \
-            --set-as-default false \
-            --ignore-prerequisites \
-            --legacy-bridge
+  #         ci_run ./bin/zkt
+  #         ci_run zk_inception chain create \
+  #           --chain-name legacy \
+  #           --chain-id sequential \
+  #           --prover-mode no-proofs \
+  #           --wallet-creation localhost \
+  #           --l1-batch-commit-data-generator-mode rollup \
+  #           --base-token-address 0x0000000000000000000000000000000000000001 \
+  #           --base-token-price-nominator 1 \
+  #           --base-token-price-denominator 1 \
+  #           --set-as-default false \
+  #           --ignore-prerequisites \
+  #           --legacy-bridge
           
-          ci_run zk_inception ecosystem init --dev --verbose
-          ci_run zk_supervisor contracts --test-contracts
+  #         ci_run zk_inception ecosystem init --dev --verbose
+  #         ci_run zk_supervisor contracts --test-contracts
 
-      # `sleep 60` because we need to wait until server added all the tokens
-      - name: Run server
-        run: |
-          ci_run sed -i -e 's/mode: FULL/mode: LIGHTWEIGHT/' chains/legacy/configs/general.yaml
-          ci_run sed -i -e 's/state_keeper_fast_vm_mode:.*/state_keeper_fast_vm_mode: ${{ matrix.vm_mode }}/' chains/legacy/configs/general.yaml
-          ci_run sed -i -e 's/delay_interval:.*/delay_interval: 50/' chains/legacy/configs/general.yaml
-          ci_run zk_inception server --uring --chain=legacy --components api,tree,eth,state_keeper,housekeeper,commitment_generator,vm_runner_protective_reads &>server.log &
-          ci_run sleep 60
+  #     # `sleep 60` because we need to wait until server added all the tokens
+  #     - name: Run server
+  #       run: |
+  #         ci_run sed -i -e 's/mode: FULL/mode: LIGHTWEIGHT/' chains/legacy/configs/general.yaml
+  #         ci_run sed -i -e 's/state_keeper_fast_vm_mode:.*/state_keeper_fast_vm_mode: ${{ matrix.vm_mode }}/' chains/legacy/configs/general.yaml
+  #         ci_run sed -i -e 's/delay_interval:.*/delay_interval: 50/' chains/legacy/configs/general.yaml
+  #         ci_run zk_inception server --uring --chain=legacy --components api,tree,eth,state_keeper,housekeeper,commitment_generator,vm_runner_protective_reads &>server.log &
+  #         ci_run sleep 60
 
-      - name: Perform loadtest
-        run: ci_run zk_supervisor t loadtest -v --chain=legacy
+  #     - name: Perform loadtest
+  #       run: ci_run zk_supervisor t loadtest -v --chain=legacy
 
-      - name: Show server.log logs
-        if: always()
-        run: ci_run cat server.log || true
+  #     - name: Show server.log logs
+  #       if: always()
+  #       run: ci_run cat server.log || true
 
-      - name: Show sccache logs
-        if: always()
-        run: |
-          ci_run sccache --show-stats || true
-          ci_run cat /tmp/sccache_log.txt || true
+  #     - name: Show sccache logs
+  #       if: always()
+  #       run: |
+  #         ci_run sccache --show-stats || true
+  #         ci_run cat /tmp/sccache_log.txt || true
 
   integration:
     name: Integration (consensus=${{ matrix.consensus }}, base_token=${{ matrix.base_token }}, gateway = ${{ matrix.gateway }})
