ci: Added multiarch pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -125,17 +125,17 @@ jobs:
   #     DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
   #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
 
-  ci-success:
-    name: Github Status Check
-    runs-on: ubuntu-latest
-    if: always() && !cancelled()
-    needs: [ci-for-core-lint, ci-for-core, ci-for-prover, ci-for-docs, build-core-images, build-prover-images]
-    steps:
-      - name: Status
-        run: |
-          # This will check all jobs status in the `needs` list, and fail job if one is failed.
-          # Since we split prover and core to different flows, this job will be only as Required Status Check in the Pull Request.
-          if [[ ${{ contains(join(needs.*.result, ','), 'failure') }} == "true" ]]; then
-            echo "Intentionally failing to block PR from merging"
-            exit 1
-          fi
+  # ci-success:
+  #   name: Github Status Check
+  #   runs-on: ubuntu-latest
+  #   if: always() && !cancelled()
+  #   needs: [ci-for-core-lint, ci-for-core, ci-for-prover, ci-for-docs, build-core-images, build-prover-images]
+  #   steps:
+  #     - name: Status
+  #       run: |
+  #         # This will check all jobs status in the `needs` list, and fail job if one is failed.
+  #         # Since we split prover and core to different flows, this job will be only as Required Status Check in the Pull Request.
+  #         if [[ ${{ contains(join(needs.*.result, ','), 'failure') }} == "true" ]]; then
+  #           echo "Intentionally failing to block PR from merging"
+  #           exit 1
+  #         fi
