ci: Added multiarch pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -73,34 +73,34 @@ jobs:
               - '!**/*.md'
               - '!**/*.MD'
 
-  # ci-for-core-lint:
-  #   name: CI for Core lint Components
-  #   needs: changed_files
-  #   if: contains(github.ref_name, 'release-please--branches')
-  #   uses: ./.github/workflows/ci-core-lint-reusable.yml
+  ci-for-core-lint:
+    name: CI for Core lint Components
+    needs: changed_files
+    if: contains(github.ref_name, 'release-please--branches')
+    uses: ./.github/workflows/ci-core-lint-reusable.yml
 
-  # ci-for-core:
-  #   name: CI for Core Components
-  #   needs: changed_files
-  #   if: ${{ (needs.changed_files.outputs.core == 'true' || needs.changed_files.outputs.all == 'true') && !contains(github.ref_name, 'release-please--branches') }}
-  #   uses: ./.github/workflows/ci-core-reusable.yml
+  ci-for-core:
+    name: CI for Core Components
+    needs: changed_files
+    if: ${{ (needs.changed_files.outputs.core == 'true' || needs.changed_files.outputs.all == 'true') && !contains(github.ref_name, 'release-please--branches') }}
+    uses: ./.github/workflows/ci-core-reusable.yml
 
-  # ci-for-prover:
-  #   needs: changed_files
-  #   if: ${{ (needs.changed_files.outputs.prover == 'true' || needs.changed_files.outputs.all == 'true') && !contains(github.ref_name, 'release-please--branches') }}
-  #   name: CI for Prover Components
-  #   uses: ./.github/workflows/ci-prover-reusable.yml
+  ci-for-prover:
+    needs: changed_files
+    if: ${{ (needs.changed_files.outputs.prover == 'true' || needs.changed_files.outputs.all == 'true') && !contains(github.ref_name, 'release-please--branches') }}
+    name: CI for Prover Components
+    uses: ./.github/workflows/ci-prover-reusable.yml
 
-  # ci-for-docs:
-  #   needs: changed_files
-  #   if: needs.changed_files.outputs.docs == 'true'
-  #   name: CI for Docs
-  #   uses: ./.github/workflows/ci-docs-reusable.yml
+  ci-for-docs:
+    needs: changed_files
+    if: needs.changed_files.outputs.docs == 'true'
+    name: CI for Docs
+    uses: ./.github/workflows/ci-docs-reusable.yml
 
   build-core-images:
     name: Build core images
-    # needs: changed_files
-    # if: ${{ (needs.changed_files.outputs.core == 'true' || needs.changed_files.outputs.all == 'true') && !contains(github.ref_name, 'release-please--branches') }}
+    needs: changed_files
+    if: ${{ (needs.changed_files.outputs.core == 'true' || needs.changed_files.outputs.all == 'true') && !contains(github.ref_name, 'release-please--branches') }}
     uses: ./.github/workflows/build-core-template.yml
     with:
       image_tag: ${{ needs.setup.outputs.image_tag }}
@@ -110,32 +110,32 @@ jobs:
       DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
       DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
 
-  # build-prover-images:
-  #   name: Build prover images
-  #   needs: changed_files
-  #   if: ${{ (needs.changed_files.outputs.prover == 'true' || needs.changed_files.outputs.all == 'true') && !contains(github.ref_name, 'release-please--branches') }}
-  #   uses: ./.github/workflows/build-prover-template.yml
-  #   with:
-  #     image_tag: ${{ needs.setup.outputs.image_tag }}
-  #     image_tag_suffix: ${{ needs.setup.outputs.image_tag_suffix }}
-  #     action: "build"
-  #     ERA_BELLMAN_CUDA_RELEASE: ${{ vars.ERA_BELLMAN_CUDA_RELEASE }}
-  #     is_pr_from_fork: ${{ github.event.pull_request.head.repo.fork == true }}
-  #   secrets:
-  #     DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
-  #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
+  build-prover-images:
+    name: Build prover images
+    needs: changed_files
+    if: ${{ (needs.changed_files.outputs.prover == 'true' || needs.changed_files.outputs.all == 'true') && !contains(github.ref_name, 'release-please--branches') }}
+    uses: ./.github/workflows/build-prover-template.yml
+    with:
+      image_tag: ${{ needs.setup.outputs.image_tag }}
+      image_tag_suffix: ${{ needs.setup.outputs.image_tag_suffix }}
+      action: "build"
+      ERA_BELLMAN_CUDA_RELEASE: ${{ vars.ERA_BELLMAN_CUDA_RELEASE }}
+      is_pr_from_fork: ${{ github.event.pull_request.head.repo.fork == true }}
+    secrets:
+      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
+      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
 
-  # ci-success:
-  #   name: Github Status Check
-  #   runs-on: ubuntu-latest
-  #   if: always() && !cancelled()
-  #   needs: [ci-for-core-lint, ci-for-core, ci-for-prover, ci-for-docs, build-core-images, build-prover-images]
-  #   steps:
-  #     - name: Status
-  #       run: |
-  #         # This will check all jobs status in the `needs` list, and fail job if one is failed.
-  #         # Since we split prover and core to different flows, this job will be only as Required Status Check in the Pull Request.
-  #         if [[ ${{ contains(join(needs.*.result, ','), 'failure') }} == "true" ]]; then
-  #           echo "Intentionally failing to block PR from merging"
-  #           exit 1
-  #         fi
+  ci-success:
+    name: Github Status Check
+    runs-on: ubuntu-latest
+    if: always() && !cancelled()
+    needs: [ci-for-core-lint, ci-for-core, ci-for-prover, ci-for-docs, build-core-images, build-prover-images]
+    steps:
+      - name: Status
+        run: |
+          # This will check all jobs status in the `needs` list, and fail job if one is failed.
+          # Since we split prover and core to different flows, this job will be only as Required Status Check in the Pull Request.
+          if [[ ${{ contains(join(needs.*.result, ','), 'failure') }} == "true" ]]; then
+            echo "Intentionally failing to block PR from merging"
+            exit 1
+          fi
