ci: Fixing permissions for workflow to label external contributions, take 2

diff --git a/.github/workflows/label-extenal-contributions.yml b/.github/workflows/label-extenal-contributions.yml
--- a/.github/workflows/label-extenal-contributions.yml
+++ b/.github/workflows/label-extenal-contributions.yml
@@ -5,7 +5,8 @@ on:
     types: [opened, ready_for_review]
 
 permissions:
-  issues: write
+  contents: read
+  pull-requests: write
 
 jobs:
   label:
@@ -21,12 +22,17 @@ jobs:
 
         if [[ "$IS_FORK" == "true" ]]; then
             echo "This PR is created from a fork."
-            curl \
+            HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" \
             -X POST \
             -H "Authorization: Bearer $GITHUB_TOKEN" \
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/repos/$REPO_FULL_NAME/issues/$PR_NUMBER/labels" \
-            -d '{"labels": ["external-contribution"]}'
+            -d '{"labels": ["external-contribution"]}')
+
+            if [[ $HTTP_STATUS -ge 300 ]]; then
+                echo "Failed to add label to PR, exiting."
+                exit 1
+            fi
         else
             echo "This PR is not created from a fork."
         fi
