continue refactoring

diff --git a/.github/workflows/TEST_prover.yaml b/.github/workflows/TEST_prover.yaml
--- a/.github/workflows/TEST_prover.yaml
+++ b/.github/workflows/TEST_prover.yaml
@@ -13,25 +13,25 @@ permissions:
 
 # Define the events that triggers the workflow
 on:
-  pull_request:
-    paths:
-      # Workspaces
-      - 'prover/**'
-      - 'zkstack_cli/**'
-      - '!prover/CHANGELOG.md'
-      - '!prover/setup-data-cpu-keys.json'
-      - '!prover/setup-data-gpu-keys.json'
-      - '!prover/extract-setup-data-keys.sh'
-      # Docker files
-      - 'docker/prover*/**'
-      - 'docker-compose-runner-nightly.yml'
-      # CI scripts
-      - '.github/workflows/prover.yaml'
-      - '.github/workflows/build-prover-template.yml'            # TODO: check name after refactoring
-      - '.github/workflows/build-witness-generator-template.yml' # TODO: check name after refactoring
-      # Exclude markdown files
-      - '!**/*.md'
-      - '!**/*.MD'
+#  pull_request:
+#    paths:
+#      # Workspaces
+#      - 'prover/**'
+#      - 'zkstack_cli/**'
+#      - '!prover/CHANGELOG.md'
+#      - '!prover/setup-data-cpu-keys.json'
+#      - '!prover/setup-data-gpu-keys.json'
+#      - '!prover/extract-setup-data-keys.sh'
+#      # Docker files
+#      - 'docker/prover*/**'
+#      - 'docker-compose-runner-nightly.yml'
+#      # CI scripts
+#      - '.github/workflows/prover.yaml'
+#      - '.github/workflows/build-prover-template.yml'            # TODO: check name after refactoring
+#      - '.github/workflows/build-witness-generator-template.yml' # TODO: check name after refactoring
+#      # Exclude markdown files
+#      - '!**/*.md'
+#      - '!**/*.MD'
   merge_group:
 
 # Cancel previous runs for PRs if new one is started
@@ -90,35 +90,35 @@ jobs:
   #
   # Runs cargo test in CI environment.
   # =================================================
-#  unit-tests:
-#    name: Unit tests
-#    runs-on: matterlabs-ci-runner-highmem-long
-#    needs: changed-files
-#    if: ${{ needs.changed-files.outputs.any_changed == 'true' }}
-#    steps:
-#      - name: Checkout
-#        uses: actions/checkout@v4
-#        with:
-#          submodules: "recursive"
-#
-#      - name: Setup runner
-#        uses: matter-labs/zksync-ci-common/.github/actions/runner-setup@aba-ci-optimize
-#        with:
-#          workspace: 'prover'     # Use prover workspace cache setup
-#          cache_shared_key: 'dev' # Use `dev` profile cache to significantly speed up the build
-#
-#      # Download prebuilt contracts version if exists, otherwise build them
-#      - name: Setup contracts
-#        uses: matter-labs/zksync-ci-common/.github/actions/build-contracts@aba-ci-optimize
-#
-#      - name: Start services
-#        run: docker-compose up -d --wait postgres
-#
-#      # Not all tests are enabled
-#      # since prover and setup_key_generator_and_server
-#      # requires bellman-cuda to be present
-#      - name: Unit tests
-#        run: zkstack dev test prover
+  unit-tests:
+    name: Unit tests
+    runs-on: matterlabs-ci-runner-highmem-long
+    needs: changed-files
+    if: ${{ needs.changed-files.outputs.any_changed == 'true' }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          submodules: "recursive"
+
+      - name: Setup runner
+        uses: matter-labs/zksync-ci-common/.github/actions/runner-setup@aba-ci-optimize
+        with:
+          workspace: 'prover'     # Use prover workspace cache setup
+          cache_shared_key: 'dev' # Use `dev` profile cache to significantly speed up the build
+
+      # Download prebuilt contracts version if exists, otherwise build them
+      - name: Setup contracts
+        uses: matter-labs/zksync-ci-common/.github/actions/build-contracts@aba-ci-optimize
+
+      - name: Start services
+        run: docker-compose up -d --wait postgres
+
+      # Not all tests are enabled
+      # since prover and setup_key_generator_and_server
+      # requires bellman-cuda to be present
+      - name: Unit tests
+        run: zkstack dev test prover
 
   e2e-tests:
     runs-on: matterlabs-ci-gpu-l4-runner-prover-tests
@@ -268,14 +268,18 @@ jobs:
   # requiring others to be successful.
   # This is used to block PRs from merging without passing CI.
   # ====================================================================
-  required-check:
+  ci-success:
     name: Github Status Check
     runs-on: ubuntu-latest
     if: always() && !cancelled()
     needs:
-#      - unit-tests
+      - unit-tests
       - e2e-tests
     steps:
-      - uses: re-actors/alls-green@release/v1
-        with:
-          jobs: ${{ toJSON(needs) }}
+      - name: Status
+        run: |
+          # This will check all jobs status in the `needs` list, and fail job if one is failed.
+          if [[ ${{ contains(join(needs.*.result, ','), 'failure') }} == "true" ]]; then
+            echo "Intentionally failing to block PR from merging"
+            exit 1
+          fi
