refactor: move Cargo.toml from root to core workspace (#3456)
## What ❔

Move `Cargo.toml` from repository root to `core` workspace.

<!-- What are the changes this PR brings about? -->
<!-- Example: This PR adds a PR template to the repo. -->
<!-- (For bigger PRs adding more context is appreciated) -->

## Why ❔

It is mandatory for proper separation of workspaces and setting up a
`release-please` CI that requires all files of a component to be inside
the component directory.

## CI failures

Currently, the following tests are failing:
* `protobuf_compatibility` - the workflow is using base version and will
be fixed with the next PRs after merge to `main`.

<!-- Why are these changes done? What goal do they contribute to? What
are the principles behind them? -->
<!-- Example: PR templates ensure PR reviewers, observers, and future
iterators are in context about the evolution of repos. -->

## Checklist

<!-- Check your PR fulfills the following items. -->
<!-- For draft PRs check the boxes as you complete them. -->

- [x] PR title corresponds to the body of PR (we generate changelog
entries from PRs).
- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Code has been formatted via `zkstack dev fmt` and `zkstack dev
lint`.

diff --git a/.github/workflows/vm-perf-comparison.yml b/.github/workflows/vm-perf-comparison.yml
--- a/.github/workflows/vm-perf-comparison.yml
+++ b/.github/workflows/vm-perf-comparison.yml
@@ -53,8 +53,10 @@ jobs:
         run: |
           ci_run zkstackup -g --local
           ci_run zkstack dev contracts
-          ci_run cargo bench --package vm-benchmark --bench instructions -- --verbose || echo "Instructions benchmark is missing"
-          ci_run cargo run --package vm-benchmark --release --bin instruction_counts | tee base-opcodes
+          ci_run cargo bench --manifest-path ./core/Cargo.toml \
+            --package vm-benchmark --bench instructions -- --verbose || echo "Instructions benchmark is missing"
+          ci_run cargo run --manifest-path ./core/Cargo.toml \
+            --package vm-benchmark --release --bin instruction_counts | tee base-opcodes
 
       - name: checkout PR
         run: |
@@ -69,7 +71,8 @@ jobs:
           ci_run zkstack dev contracts
           ci_run cargo bench --package vm-benchmark --bench instructions -- --verbose
 
-          ci_run cargo bench --package vm-benchmark --bench instructions -- --print > instructions.log 2>/dev/null
+          ci_run cargo bench --manifest-path ./core/Cargo.toml \
+            --package vm-benchmark --bench instructions -- --print > instructions.log 2>/dev/null
           # Output all lines from the benchmark result starting from the "## ..." comparison header.
           # Since the output spans multiple lines, we use a heredoc declaration.
           EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
@@ -77,7 +80,8 @@ jobs:
           sed -n '/^## /,$p' instructions.log >> $GITHUB_OUTPUT
           echo "$EOF" >> $GITHUB_OUTPUT
           
-          ci_run cargo run --package vm-benchmark --release --bin instruction_counts -- --diff base-opcodes > opcodes.log
+          ci_run cargo run --manifest-path ./core/Cargo.toml \
+            --package vm-benchmark --release --bin instruction_counts -- --diff base-opcodes > opcodes.log
           echo "opcodes<<$EOF" >> $GITHUB_OUTPUT
           sed -n '/^## /,$p' opcodes.log >> $GITHUB_OUTPUT
           echo "$EOF" >> $GITHUB_OUTPUT
